# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

haversine_cpp <- function(lon1, lat1, lon2, lat2, radius = 6371.0088) {
    .Call(`_palsr_haversine_cpp`, lon1, lat1, lon2, lat2, radius)
}

project_one_cpp <- function(focal_age, focal_lon, focal_lat, alter_age, alter_lon, alter_lat, alpha, beta, gamma, eta, pi_zero = FALSE, alter_legacy = FALSE, eps = 0.01) {
    .Call(`_palsr_project_one_cpp`, focal_age, focal_lon, focal_lat, alter_age, alter_lon, alter_lat, alpha, beta, gamma, eta, pi_zero, alter_legacy, eps)
}

project_batch_cpp <- function(f_age, f_lon, f_lat, f_off, f_len, k_age, k_lon, k_lat, k_off, k_len, alpha, beta, gamma, eta, pi_zero = FALSE, alter_legacy = FALSE, eps = 0.01) {
    .Call(`_palsr_project_batch_cpp`, f_age, f_lon, f_lat, f_off, f_len, k_age, k_lon, k_lat, k_off, k_len, alpha, beta, gamma, eta, pi_zero, alter_legacy, eps)
}

