// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// haversine_cpp
NumericVector haversine_cpp(NumericVector lon1, NumericVector lat1, NumericVector lon2, NumericVector lat2, double radius);
RcppExport SEXP _palsr_haversine_cpp(SEXP lon1SEXP, SEXP lat1SEXP, SEXP lon2SEXP, SEXP lat2SEXP, SEXP radiusSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type lon1(lon1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lat1(lat1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lon2(lon2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lat2(lat2SEXP);
    Rcpp::traits::input_parameter< double >::type radius(radiusSEXP);
    rcpp_result_gen = Rcpp::wrap(haversine_cpp(lon1, lat1, lon2, lat2, radius));
    return rcpp_result_gen;
END_RCPP
}
// project_one_cpp
NumericVector project_one_cpp(NumericVector focal_age, NumericVector focal_lon, NumericVector focal_lat, NumericVector alter_age, NumericVector alter_lon, NumericVector alter_lat, double alpha, double beta, double gamma, double eta, bool pi_zero, bool alter_legacy, double eps);
RcppExport SEXP _palsr_project_one_cpp(SEXP focal_ageSEXP, SEXP focal_lonSEXP, SEXP focal_latSEXP, SEXP alter_ageSEXP, SEXP alter_lonSEXP, SEXP alter_latSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP gammaSEXP, SEXP etaSEXP, SEXP pi_zeroSEXP, SEXP alter_legacySEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type focal_age(focal_ageSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type focal_lon(focal_lonSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type focal_lat(focal_latSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alter_age(alter_ageSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alter_lon(alter_lonSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alter_lat(alter_latSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< bool >::type pi_zero(pi_zeroSEXP);
    Rcpp::traits::input_parameter< bool >::type alter_legacy(alter_legacySEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(project_one_cpp(focal_age, focal_lon, focal_lat, alter_age, alter_lon, alter_lat, alpha, beta, gamma, eta, pi_zero, alter_legacy, eps));
    return rcpp_result_gen;
END_RCPP
}
// project_batch_cpp
NumericMatrix project_batch_cpp(NumericVector f_age, NumericVector f_lon, NumericVector f_lat, IntegerVector f_off, IntegerVector f_len, NumericVector k_age, NumericVector k_lon, NumericVector k_lat, IntegerVector k_off, IntegerVector k_len, double alpha, double beta, double gamma, double eta, bool pi_zero, bool alter_legacy, double eps);
RcppExport SEXP _palsr_project_batch_cpp(SEXP f_ageSEXP, SEXP f_lonSEXP, SEXP f_latSEXP, SEXP f_offSEXP, SEXP f_lenSEXP, SEXP k_ageSEXP, SEXP k_lonSEXP, SEXP k_latSEXP, SEXP k_offSEXP, SEXP k_lenSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP gammaSEXP, SEXP etaSEXP, SEXP pi_zeroSEXP, SEXP alter_legacySEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type f_age(f_ageSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type f_lon(f_lonSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type f_lat(f_latSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type f_off(f_offSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type f_len(f_lenSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type k_age(k_ageSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type k_lon(k_lonSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type k_lat(k_latSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type k_off(k_offSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type k_len(k_lenSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< bool >::type pi_zero(pi_zeroSEXP);
    Rcpp::traits::input_parameter< bool >::type alter_legacy(alter_legacySEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(project_batch_cpp(f_age, f_lon, f_lat, f_off, f_len, k_age, k_lon, k_lat, k_off, k_len, alpha, beta, gamma, eta, pi_zero, alter_legacy, eps));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_palsr_haversine_cpp", (DL_FUNC) &_palsr_haversine_cpp, 5},
    {"_palsr_project_one_cpp", (DL_FUNC) &_palsr_project_one_cpp, 13},
    {"_palsr_project_batch_cpp", (DL_FUNC) &_palsr_project_batch_cpp, 17},
    {NULL, NULL, 0}
};

RcppExport void R_init_palsr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
